name: nutri_fit_pro
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.6.7
  cached_network_image: ^3.3.0
  google_nav_bar: ^5.0.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  firebase_auth: ^4.17.6
  image_picker: ^0.8.4+3 
  shared_preferences: ^2.0.0
  flutter_lints: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

 
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/
  - assets/images/
  - assets/foods.json
fonts: 
  - family: Signika
    fonts: 
      - asset: assets/fonts/SignikaSemiBold.ttf
        weight: 600
      - asset: assets/fonts/SignikaRegular.ttf
        weight: 400
      - asset: assets/fonts/SignikaLight.ttf
        weight: 300
      - asset: assets/fonts/SignikaMedium.ttf
        weight: 500
  - family: Poppins
    fonts: 
      - asset: assets/fonts/PoppinsBold.ttf
        weight: 700
      - asset: assets/fonts/PoppinsSemiBold.ttf
        weight: 600
      - asset: assets/fonts/PoppinsMedium.ttf
        weight: 500
  - family: Inter
    fonts: 
      - asset: assets/fonts/InterRegular.ttf
        weight: 400
      - asset: assets/fonts/InterMedium.ttf
        weight: 500


  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-Bold.ttf
        weight: 700
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

