// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXLOM7UfpS5CCnSvJ2F9NvcHl6X76SSEE',
    appId: '1:237412426748:web:210823709d9e939c068879',
    messagingSenderId: '237412426748',
    projectId: 'nutrifitpro-f6cfc',
    authDomain: 'nutrifitpro-f6cfc.firebaseapp.com',
    databaseURL: 'https://nutrifitpro-f6cfc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrifitpro-f6cfc.appspot.com',
    measurementId: 'G-029BX83SHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5YJReS5rtzbl5upur5LgwgRnjgxRS8Fk',
    appId: '1:237412426748:android:106db07cc6a74950068879',
    messagingSenderId: '237412426748',
    projectId: 'nutrifitpro-f6cfc',
    databaseURL: 'https://nutrifitpro-f6cfc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrifitpro-f6cfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Fv65ZMxUqz0m3x20HPm0i75i_ln6IqQ',
    appId: '1:237412426748:ios:9d3f4fd2a6021d22068879',
    messagingSenderId: '237412426748',
    projectId: 'nutrifitpro-f6cfc',
    databaseURL: 'https://nutrifitpro-f6cfc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrifitpro-f6cfc.appspot.com',
    iosBundleId: 'com.example.nutriFitPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Fv65ZMxUqz0m3x20HPm0i75i_ln6IqQ',
    appId: '1:237412426748:ios:e1ab0ad7d3413c4e068879',
    messagingSenderId: '237412426748',
    projectId: 'nutrifitpro-f6cfc',
    databaseURL: 'https://nutrifitpro-f6cfc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrifitpro-f6cfc.appspot.com',
    iosBundleId: 'com.example.nutriFitPro.RunnerTests',
  );
}
